import { GetServerSideProps, NextPage } from 'next'
import axios from 'axios'
import Head from 'next/head'
import PokemonCard from '@/components/PokemonCard'
import { GetPokemonData, Pokemon } from '@/types'

const Home: NextPage<{ pokemonsData: Pokemon[] }> = ({ pokemonsData }) => {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="App">
        <h1>My pokemons</h1>
        <div>
          {pokemonsData.map(({ id, name, sprites, types }) => {
            return (
              <PokemonCard
                key={name}
                id={id}
                name={name}
                sprites={sprites}
                types={types}
              />
            )
          })}
        </div>
      </main>
    </>
  )
}

const getPokemonURL = (id: number): string =>
  `https://pokeapi.co/api/v2/pokemon/${id}`

const generatePokemonPromises = () => {
  return Array<number>(150)
    .fill(150)
    .map((_, index) =>
      axios
        .get<GetPokemonData>(getPokemonURL(index + 1))
        .then(({ data }) => data)
        .catch(error => {
          if (axios.isAxiosError(error)) {
            console.log('error message: ', error.message)
            return error.message
          } else {
            console.log('unexpected error: ', error)
            return 'An unexpected error occurred'
          }
        }),
    )
}

export const getServerSideProps: GetServerSideProps = async context => {
  const pokemonPromises = generatePokemonPromises()

  const pokemonsData = await Promise.all(pokemonPromises).then(
    pokemons => pokemons,
  )

  return {
    props: { pokemonsData },
  }
}

export default Home
